name: deploy the microservice
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
               
            - name: Build and push user-service
              uses: docker/build-push-action@v2
              with:
                    context: .
                    file: ./user-service/Dockerfile
                    push: true
                    tags: ${{secrets.DOCKERHUB_USERNAME}}/user-service:${{github.sha}}
             
            - name: Build and push product-service
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./product-service/Dockerfile
                  push: true
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/product-service:${{github.sha}}
                  
            - name: Build and push api-gateway
              uses: docker/build-push-action@V2
              with:
                 context: .
                 file: ./api-gateway/Dockerfile
                 push: true
                 tags: ${{secrets.DOCKERHUB_USERNAME}}/api-gateway:${{github.sha}}

            - name: Build and push frontend
              uses: docker/build-push-action@v2
              with:
                 context: .
                 file: ./frontend/Dockerfile
                 push: true
                 tags: ${{secrets.DOCKERHUB_USERNAME}}/frontend:${{github.sha}}
   

